apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../2.1.b-routing-tls-single-upstream
- virtualdestination.yaml

patchesStrategicMerge:
- patch/match-all-ingressgateway.yaml
- patch/route-table.yaml