# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of resources to be Applied
resources:
- gloo-mesh-gateways-workspacesettings.yaml
- north-south-gw-80.yaml
- north-south-gw-443.yaml