---
# Source: gateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-eastwestgateway
  namespace: istio-gateways
  labels:
    helm.sh/chart: gateway-1.15.1
    app: istio-eastwestgateway
    istio: "eastwestgateway"
    app.kubernetes.io/version: "1.15.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-eastwestgateway
    "istio.io/rev": "1-15"
    "topology.istio.io/network": "network1"
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-eastwestgateway
  namespace: istio-gateways
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
# Source: gateway/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-eastwestgateway
  namespace: istio-gateways
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-eastwestgateway
subjects:
- kind: ServiceAccount
  name: istio-eastwestgateway
---
# Source: gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-eastwestgateway
  namespace: istio-gateways
  labels:
    helm.sh/chart: gateway-1.15.1
    app: istio-eastwestgateway
    istio: "eastwestgateway"
    app.kubernetes.io/version: "1.15.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-eastwestgateway
    "istio.io/rev": "1-15"
    "topology.istio.io/network": "network1"
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
spec:
  type: LoadBalancer
  ports:
    - name: tcp-status-port
      port: 15021
      targetPort: 15021
    - name: tls
      port: 15443
      targetPort: 15443
    - name: tcp-istiod
      port: 15012
      targetPort: 15012
    - name: tcp-webhook
      port: 15017
      targetPort: 15017
  selector:
    app: istio-eastwestgateway
    istio: "eastwestgateway"
---
# Source: gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-eastwestgateway
  namespace: istio-gateways
  labels:
    helm.sh/chart: gateway-1.15.1
    app: istio-eastwestgateway
    istio: "eastwestgateway"
    app.kubernetes.io/version: "1.15.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-eastwestgateway
    "istio.io/rev": "1-15"
    "topology.istio.io/network": "network1"
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
spec:
  selector:
    matchLabels:
      app: istio-eastwestgateway
      istio: "eastwestgateway"
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        sidecar.istio.io/inject: "true"
        istio.io/rev: 1-15
        app: istio-eastwestgateway
        istio: "eastwestgateway"
    spec:
      serviceAccountName: istio-eastwestgateway
      securityContext:
        # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
      containers:
        - name: istio-proxy
          # "auto" will be populated at runtime by the mutating webhook. See https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection
          image: auto
          securityContext:
            # Safe since 1.22: https://github.com/kubernetes/kubernetes/pull/103326
            capabilities:
              drop:
              - ALL
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 1337
            runAsGroup: 1337
            runAsNonRoot: true
          env:
          - name: ISTIO_META_REQUESTED_NETWORK_VIEW
            value: "network1"
          - name: ISTIO_META_ROUTER_MODE
            value: "sni-dnat"
          ports:
          - containerPort: 15090
            protocol: TCP
            name: http-envoy-prom
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: gateway/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: istio-eastwestgateway
  namespace: istio-gateways
  labels:
    helm.sh/chart: gateway-1.15.1
    app: istio-eastwestgateway
    istio: "eastwestgateway"
    app.kubernetes.io/version: "1.15.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-eastwestgateway
    "istio.io/rev": "1-15"
    "topology.istio.io/network": "network1"
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-eastwestgateway
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
