apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: productpage
  namespace: bookinfo-frontends
spec:
      - opaAuth:
          modules:
          - name: allow-solo-email-users
            namespace: bookinfo-frontends
          query: "data.test.allow == true"