apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../2.1.b-routing-tls-single-upstream
- ratelimitclientconfig.yaml
- ratelimitserverconfig.yaml
- ratelimitserversettings.yaml
- ratelimitpolicy.yaml

patchesStrategicMerge:
- patch/enable-rate-limiting.yaml