apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitClientConfig
metadata:
  name: productpage
  namespace: bookinfo-frontends
  labels:
    workspace.solo.io/exported: "true"
spec:
  raw:
    rateLimits:
    - setActions:
      - requestHeaders:
          descriptorKey: number
          headerName: x-number
      - requestHeaders:
          descriptorKey: type
          headerName: x-type