apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gm-enterprise-agent-mgmt
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-mesh
  source:
    repoURL: 'https://storage.googleapis.com/gloo-mesh-enterprise/gloo-mesh-agent'
    targetRevision: 2.1.0-rc3
    chart: gloo-mesh-agent
    helm:
      skipCrds: true
      #valueFiles:
      #  - values.yaml
      parameters:
        - name: cluster
          value: 'cluster1'
        - name: relay.serverAddress
          value: '${GM_MGMT_SERVER_ADDRESS}:9900'
        - name: relay.authority
          value: 'gloo-mesh-mgmt-server.gloo-mesh'
        - name: ext-auth-service.enabled
          value: 'false'
        - name: rate-limiter.enabled
          value: 'false'
        - name: glooMeshAgent.enabled
          value: 'true'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true
    - ApplyOutOfSyncOnly=true
  project: default
