licenseSecretName: gloo-mesh-license
global:
  cluster: mgmt
mgmtClusterName: mgmt
glooMeshMgmtServer:
  serviceType: LoadBalancer
  relay:
    disableCa: true
    disableCaCertGeneration: true
    disableTokenGeneration: true
    tlsSecret:
      name: gloo-server-tls-cert
  ports:
    healthcheck: 8091
glooMeshUi:
  serviceType: ClusterIP
  enabled: true