cluster: leaf1
relay:
  serverAddress: 172.22.0.3:9900
  authority: gloo-mesh-mgmt-server.gloo-mesh
  clientTlsSecret:
    name: gloo-agent-tls-cert
ext-auth-service:
  enabled: false
rate-limiter:
  enabled: false
glooMeshAgent:
  enabled: true